"""add love languages

Revision ID: 5fc9d3875f9f
Revises: dddcab397c97
Create Date: 2026-09-01 17:11:52.144010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc9d3875f9f'
down_revision = 'dddcab397c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dating_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('love_languages', sa.Text(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_message_conv_created'))

    with op.batch_alter_table('swipe_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_swipe_swiper_action'))
        batch_op.drop_index(batch_op.f('idx_swipe_target_swiper'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swipe_interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_swipe_target_swiper'), ['swiper_id', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_swipe_swiper_action'), ['swiper_id', 'action', 'created_at'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_message_conv_created'), ['conversation_id', 'created_at'], unique=False)

    with op.batch_alter_table('dating_profile', schema=None) as batch_op:
        batch_op.drop_column('love_languages')

    # ### end Alembic commands ###
