"""add dating fields

Revision ID: dddcab397c97
Revises: 60ed52d69615
Create Date: 2026-09-01 16:43:11.294924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddcab397c97'
down_revision = '60ed52d69615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_post')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('user1_read_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('user2_read_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('dating_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('red_flags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('green_flags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('campus_spot', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('campus_spot_updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_message_conv_created'))

    with op.batch_alter_table('swipe_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_swipe_swiper_action'))
        batch_op.drop_index(batch_op.f('idx_swipe_target_swiper'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swipe_interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_swipe_target_swiper'), ['swiper_id', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_swipe_swiper_action'), ['swiper_id', 'action', 'created_at'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_message_conv_created'), ['conversation_id', 'created_at'], unique=False)

    with op.batch_alter_table('dating_profile', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('campus_spot_updated_at')
        batch_op.drop_column('campus_spot')
        batch_op.drop_column('green_flags')
        batch_op.drop_column('red_flags')
        batch_op.drop_column('interests')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('user2_read_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user1_read_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('room_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('room_block', sa.VARCHAR(length=50), nullable=False),
    sa.Column('room_subject', sa.VARCHAR(length=150), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('upvotes', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['room_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
